imagePullSecret: regcred
container:
  port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  livenessProbe: 
    enabled: false
  readinessProbe:
    enabled: false
  volumeMounts:
    - mountPath: /app/config/config.yaml
      subPath: config.yaml
      name: ack-vpa-updater-config
      readOnly: false
volumes:
  - name: ack-vpa-updater-config
    configMap:
      name: ack-vpa-updater-config
serviceAccountName: ack-vpa-updater
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
